vich_uploader:
    db_driver: orm

    mappings:
        publication_image:
            uri_prefix: '/public/images/publications'
            upload_destination: '%kernel.project_dir%/public/images/publications'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
